@echo off
echo Creating virtual environment...
python -m venv venv
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r Backend\requirements.txt
echo Starting FastAPI server...
uvicorn Backend.main:app --reload
